import {redirect} from "next/navigation";
import Header from "@/components/header";
import {createClient} from "@/lib/supabase/server";
import {CATEGORIES} from "@/lib/types";
import type {Card} from "@/lib/types";
import {add,del} from "./actions";
import ChangePassword from "@/components/change-password";
import MobileImagePicker from "@/components/mobile-image-picker";
export default async function AdminPage(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");const{data}=await s.from("cards").select("*").order("created_at",{ascending:false});const cards=(data??[]) as Card[];return <><Header/><main className="section page"><p className="eye">PRIVATE COLLECTION TOOL</p><h1>COLLECTION MANAGER</h1><form action={add} className="form"><h2>ADD A NEW CARD</h2><div className="formgrid"><label>NAME<input name="name" required/></label><label>CHARACTER / PLAYER<input name="character"/></label><label>CATEGORY<select name="category">{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>SET / SERIES<input name="set_name"/></label><label>CARD NUMBER<input name="card_number"/></label><label>RARITY<input name="rarity"/></label><label>GRADING COMPANY<input name="grading_company"/></label><label>GRADE<input name="grade"/></label><label>ESTIMATED VALUE<input name="estimated_value"/></label><MobileImagePicker /><label className="full">NOTES<textarea name="notes"/></label><label className="check"><input name="featured" type="checkbox"/> MARK AS A FEATURED GEM ◆</label></div><button className="btn">ADD TO COLLECTION</button></form><ChangePassword/><h2>YOUR CARDS ({cards.length})</h2>{cards.map(c=><div className="row" key={c.id}><span>{c.name}</span><small>{c.category}</small><form action={del.bind(null,c.id)}><button>REMOVE</button></form></div>)}</main></>}
